Erro de resposta do servidor: {
  code: -1007,
  msg: 'Timeout waiting for response from backend server. Send status unknown; execution status unknown.'
}
node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "AxiosError: Request failed with status code 408".] {
  code: 'ERR_UNHANDLED_REJECTION'
}

Node.js v21.2.0


-------------------------------------
node:internal/deps/undici/undici:11754
    Error.captureStackTrace(err, this);
          ^

TypeError: fetch failed
    at node:internal/deps/undici/undici:11754:11
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ws.onmessage (X:\NodeJs\Robo\FuturesFuncionando\binance-futures\index.js:42:21) {
  cause: ConnectTimeoutError: Connect Timeout Error
      at onConnectTimeout (node:internal/deps/undici/undici:6893:28)
      at node:internal/deps/undici/undici:6849:50
      at Immediate._onImmediate (node:internal/deps/undici/undici:6879:37)
      at process.processImmediate (node:internal/timers:478:21) {
    code: 'UND_ERR_CONNECT_TIMEOUT'
  }
}

Node.js v21.2.0